src/components/Button.tsx

add button reusable components with bg default [#3282B8]

style: add button reusable component

---

src/components/CustomInput.tsx

add input reusable components:
add customInput
add textarea

style: add customInput and TextArea reusable components

---

src/components/Card.tsx
tailwind.config.cjs

slicing card components, 
add custom color navy, sky, bone

style: slicing reusable card components, and add custom color

---

package-lock.json
package.json
src/components/Card.tsx
src/pages/Home.tsx
src/routes/index.tsx

slicing home page admin and employee in same page
install moment library
add new MiniCard in reusable card component, restyle some card
update routes

style: slicing home page for admin and employee with ternary

---

src/pages/auth/Login.tsx
src/routes/index.tsx
tailwind.config.cjs

add toogle show or hide password
add custom color yellow
change index Auth to auth

restyle: add toogle show/hide password and add custom color yellow

---

src/pages/Employee.tsx
src/pages/Home.tsx
src/routes/index.tsx

slicing employee page admin,
clean code import in home page
add paths in router

style: slicing employee page (admin)

---

src/pages/Records.tsx
src/routes/index.tsx

add records page for admin and employee by cookie role

style: slicing records page admin and employee ternary with cookie by role

---

src/pages/Records.tsx
src/pages/RecordsDetail.tsx
src/routes/index.tsx

add records detail page for admin
add function onclickdetail in records page admin
add paths detail page in routes

style: slicing records detail for admin

---

src/pages/RequestApproval.tsx
src/routes/index.tsx

add request aprroval page for employee
add paths request aprroval page

style: slicing request approval for employee

---

index.html
src/pages/Approval.tsx
src/pages/RequestApproval.tsx
src/routes/index.tsx

add appropval page
add paths routes for approval page
change with new <link> poppins google fonts

style: slicing approval page with conditions for admin or employee

---

src/pages/RecordsDetail.tsx

add modal details records
add modals create attendance

style: add modals in details record page (admin)

---

src/pages/Employee.tsx

add modals create employee manual
add modals import employe by csv
add modals update employee

style: slicing modals employee page admin

---

src/pages/RecordsDetail.tsx

restyle records detail page
restyle records detail madals

restyle: restyle records detail page and modals

---

src/components/Modals.tsx
src/pages/Approval.tsx

add modals detail approval admin
restyle modals2 components

style: slicing modals detail approval for admin

---

src/pages/Approval.tsx

add modals detail approval for empploye

style: slicing modals detail approval for empploye

---

src/components/Sidebar.tsx
src/pages/Approval.tsx
src/pages/CompanyProfile.tsx
src/pages/Employee.tsx
src/pages/EmployeeProfile.tsx
src/pages/Home.tsx
src/pages/Records.tsx
src/pages/RequestApproval.tsx
src/routes/index.tsx

refactor: add routing to all page

---

src/pages/auth/Login.tsx

integration login page with API
add sweetalert2 succes and failed
setCookie token, role, etc
navigate to home

feat: integration login page

---

src/components/Sidebar.tsx

integration logout button
add sweetalert with condition logout

feat: integration logout button

---

src/pages/Employee.tsx

Change onClickDetails to img, nip, name and position on employee card

fix: change the location of the onClick details on the card

---

src/pages/Employee.tsx

add id onclickdetail in img, nip, and position
add id update modals
add id delete employee card

restyle: add id onClickDetail, id update modals, and delete employe card

---

src/pages/Records.tsx

add id in records page for admin and employee

feat: add id in records page for admin and employee

---

src/pages/Approval.tsx

add id in approval page admin and employee

feat: add id in approval page admin and employee

---

src/pages/Home.tsx

integration total employe card in home page admin
integration employe card in home page admin
integration iinbox card in home page admin

feat: integration get all employee and get all inbox

---

src/pages/CompanyProfile.tsx

integration get data company
integration edit data company

feat: integration company profile page

---

src/pages/EmployeeProfile.tsx

integration data employee profile with conditions admin or employee

feat: integration data employee profile with conditions

---

src/pages/Inbox.tsx

integration get data list inbox page (admin)

feat: integration get data list inbox

---

src/pages/Inbox.tsx

integration get data inbox by id

feat: integration get data inbox by id

---

src/pages/Inbox.tsx

integration delete data inbox admin

feat: integration delete data inbox

---

src/pages/Inbox.tsx

integration delete inbox admin

feat: integration delete inbox

---

src/pages/EmployeeProfile.tsx

bug show employee by id (admin)

fix: bug show employee by id (admin)

---

src/pages/Inbox.tsx

add navigate(0) in integration post

fix: bug create inbox admin

---

src/pages/Settings.tsx

integration get data settings admin, start & end work hour, tollerance, and annual leave

feat: integration get data settings admin

---

src/pages/Settings.tsx

integration edit data setting, start and end working hour, tollerancy, and annual leave

feat: integration edit data setting

---

src/components/Navbar.tsx

integration name in navbar with cookie

feat: integration name in navbar with cookie

---

src/pages/Approval.tsx

integration show list approval admin
condition status approval with color

feat: integration show list approval

---

src/pages/RequestApproval.tsx

integration request approval from employee

feat: integration request approval from employee

---

src/pages/Inbox.tsx

show all inbox for employe type public and personal (id employe)

feat: show all inbox for employe

---

src/pages/Home.tsx

integration location employe
integration get setting work hour

feat: integration location employe

---

src/pages/Home.tsx

add logs clock in and clock out

feat: integration logs today employee

---

src/components/Navbar.tsx

fix routing logo button at navbar from "/" to "/home"

fix: fix routing logo button at navabar

---

src/pages/Home.tsx

attendances log today for employee clock in or clock out

fix: attendances log today for employee

---

src/pages/Home.tsx

integration total presences today admin

feat: integration total presences today admin

---

package-lock.json
package.json
src/pages/Home.tsx

implement chartjs-2 with data dummy

chore: implement chartjs-2 with data dummy

---

src/pages/Home.tsx

set id graphs
set style  width: 500

chore: set id graph and width

---

src/pages/Approval.tsx

Add desc approval by id modals (admin and employee)

feat: Add desc approval by id (admin & employee)

---

src/pages/Approval.tsx

add interval on leave in approval by id (bug must double click to show interval date on leave)

feat: add interval on leave in approval by id

---

package-lock.json
package.json
src/pages/Records.tsx

implement date range picker records employee show start date and end date

feat: implemenet date range picker records employee

---

src/pages/Records.tsx
src/pages/RecordsDetail.tsx

set onclickDetail send params to records employee page (admin)
integreation integration records by id employee (admin)

feat: integration records by id employee (admin)

---

src/pages/RecordsDetail.tsx

implement date picker 
integration detail record by id attendances (start and end date hardcore)

feat: integration details record with modals by id attendances (admin)

---

src/pages/RecordsDetail.tsx

implement date range picker admin

feat: implement date range picker admin

---

src/pages/RecordsDetail.tsx

integration add attendances manual from admin

feat: integration add attendances manual from admin

---

src/pages/Records.tsx

set ID and clean code (admin and employee)

chore: set ID and clean code

---

src/pages/Approval.tsx
src/pages/Employee.tsx
src/pages/GetMaps.tsx
src/pages/Home.tsx
src/pages/Inbox.tsx
src/pages/Records.tsx
src/pages/RecordsDetail.tsx

set ID interactive components all file

refactor: set ID interactive components all file

---

src/pages/Home.tsx

integration graph with api (admin),
change graph from by weekly to by one month (admin),
change routing employee to employee profile page (admin),
fix bug useEffect cant get location (employee),

feat: integration graph with api by month admin

---

src/pages/Settings.tsx

layout input office  hours
fix input default value office hours

fix: bug input office hours

---

src/pages/Approval.tsx
src/pages/CompanyProfile.tsx
src/pages/Employee.tsx
src/pages/EmployeeProfile.tsx
src/pages/Home.tsx
src/pages/Inbox.tsx
src/pages/Records.tsx
src/pages/RecordsDetail.tsx
src/pages/RequestApproval.tsx
src/pages/Settings.tsx
src/pages/auth/Login.tsx
src/utils/Type.ts

displace data type to file type.ts in utils folder
clean code import, state, alert

refactor: displace data type to file type.ts in utils folder

---

src/components/Loader.tsx
src/pages/Approval.tsx
src/pages/CompanyProfile.tsx
src/pages/Employee.tsx
src/pages/EmployeeProfile.tsx
src/pages/Inbox.tsx
src/pages/Records.tsx
src/pages/RecordsDetail.tsx
src/pages/RequestApproval.tsx
src/pages/Settings.tsx
src/styles/loader.css

add loading in function
add loading for admin page
add loading for employee page
add disabled button
add loader and loader css

refactor: add loading, disabled button, and loader

---

src/pages/Home.tsx

add loading home page admin and employee

refactor: add loading home page admin and employee

---

src/pages/EmployeeProfile.tsx
src/pages/RequestApproval.tsx

fix modals edit photo and edit password:
-text-black and font-bold on title modals
fix custom file upload to PNG and JPEG in request appproval req

refactor; fix modals and custom input file

---

README.md
src/pages/Records.tsx

update list readme about project, deploy, design, etc.
add feature as admin, and employe

docs: update readme, add feature as admin and employee

---

README.md

centered image 
change list feature

docs: centered image and change list feature

---

src/pages/Approval.tsx
src/pages/CompanyProfile.tsx
src/pages/Employee.tsx
src/pages/EmployeeProfile.tsx
src/pages/Home.tsx
src/pages/Inbox.tsx
src/pages/Records.tsx
src/pages/RecordsDetail.tsx
src/pages/RequestApproval.tsx
src/pages/Settings.tsx

clean code
fix bug all page
modify request approval page (datepickker)

feat: clean code, fix bug all page
